##importing the libiraries for deep learning CNN

In [2]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from keras.preprocessing.image import ImageDataGenerator

##pre processing the dataset

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# preprocessing over the training set

train_data_generation = ImageDataGenerator(rescale=1./255,
                                           shear_range=0.2,
                                           zoom_range=0.2,
                                           horizontal_flip=True,
                                           )

training_set = train_data_generation.flow_from_directory('/content/drive/MyDrive/DotPy/two_types of skin cancer/train',
                                                         target_size=(64, 64),
                                                         batch_size=16,
                                                         class_mode='binary')


Found 2637 images belonging to 2 classes.


In [4]:

# 1- preprocessing the testing set
test_data_generation = ImageDataGenerator(rescale=1./255)
testing_set = test_data_generation.flow_from_directory('/content/drive/MyDrive/DotPy/two_types of skin cancer/test',
                                                       target_size=(64, 64),
                                                       batch_size=16,
                                                       class_mode='binary')


Found 660 images belonging to 2 classes.


##building the model

In [5]:
model = Sequential([
            #layer 1
            Conv2D(filters=64, kernel_size=4, activation='relu', input_shape = (64, 64, 3)),
            MaxPooling2D(pool_size=2),

            #layre 2
            Conv2D(filters=32, kernel_size=3, activation='relu'),
            MaxPooling2D(pool_size=2),
            Dropout(0.2),

            Flatten(),
            Dense(units=128, activation='relu'),
            Dense(units=1, activation='sigmoid')
])


##compiling the model

In [6]:
model.compile(optimizer='SGD', loss='binary_crossentropy', metrics=['accuracy'])

##fitting the training and testing data

In [7]:
history = model.fit(x = training_set, validation_data = testing_set, epochs=10)

Epoch 1/10
165/165 [==============================] - 1155s 7s/step - loss: 0.6660 - accuracy: 0.5794 - val_loss: 0.6765 - val_accuracy: 0.5970
Epoch 2/10
165/165 [==============================] - 20s 119ms/step - loss: 0.6153 - accuracy: 0.6496 - val_loss: 0.5388 - val_accuracy: 0.7227
Epoch 3/10
165/165 [==============================] - 19s 114ms/step - loss: 0.5638 - accuracy: 0.7065 - val_loss: 0.4986 - val_accuracy: 0.7470
Epoch 4/10
165/165 [==============================] - 21s 129ms/step - loss: 0.5425 - accuracy: 0.7277 - val_loss: 0.4801 - val_accuracy: 0.7727
Epoch 5/10
165/165 [==============================] - 20s 122ms/step - loss: 0.5093 - accuracy: 0.7440 - val_loss: 0.5036 - val_accuracy: 0.7697
Epoch 6/10
165/165 [==============================] - 20s 121ms/step - loss: 0.5026 - accuracy: 0.7531 - val_loss: 0.4380 - val_accuracy: 0.7773
Epoch 7/10
165/165 [==============================] - 20s 123ms/step - loss: 0.4714 - accuracy: 0.7607 - val_loss: 0.4500 - val_acc

# save the weights

In [8]:
model.save('my_weights.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# Single prediction

In [9]:
#using the model for new predictions
from tensorflow.keras.utils import img_to_array, load_img
import numpy as np

In [11]:
image = load_img('/content/drive/MyDrive/DotPy/two_types of skin cancer/test/benign/1006.jpg', target_size=(64, 64))

image = img_to_array(image)
print(image)

image = np.expand_dims(image, axis=0)
result = model.predict(image)
print(np.argmax(result))

[[[234. 135. 156.]
  [235. 142. 163.]
  [237. 143. 169.]
  ...
  [250. 180. 204.]
  [244. 170. 187.]
  [242. 168. 185.]]

 [[230. 139. 154.]
  [235. 143. 166.]
  [234. 142. 163.]
  ...
  [245. 175. 201.]
  [247. 173. 198.]
  [241. 170. 188.]]

 [[233. 141. 156.]
  [233. 141. 164.]
  [236. 142. 166.]
  ...
  [245. 167. 191.]
  [244. 169. 189.]
  [238. 167. 185.]]

 ...

 [[218. 126. 139.]
  [216. 130. 143.]
  [223. 133. 143.]
  ...
  [225. 164. 172.]
  [222. 160. 173.]
  [221. 164. 171.]]

 [[218. 142. 155.]
  [215. 126. 144.]
  [221. 134. 150.]
  ...
  [228. 165. 173.]
  [226. 160. 170.]
  [223. 162. 170.]]

 [[218. 144. 157.]
  [223. 137. 150.]
  [220. 130. 140.]
  ...
  [225. 164. 171.]
  [224. 164. 172.]
  [217. 158. 164.]]]
1/1 [==============================] - 0s 242ms/step
0


In [12]:
if np.argmax(result) == 0:
  print(".....")

.....
